### ISSUE TITLE
Add tabs!

### ISSUE THREAD

**Issue by yuvipanda** [IonicaBizau/magnesium#9]
Allowing use of multiple shells at the same time.

**Comment by IonicaBizau** [comment]
Well, I'm not really for this because I recommend using `tmux` which has tabs. That's why I didn't think tabs are needed here and in web-term.

In `tmux` you can create a tab using <kbd>CTRL</kbd> + <kbd>b</kbd>, <kbd>c</kbd> and then you can navigate through them using <kbd>CTRL</kbd> + <kbd>b</kbd>, <kbd>0</kbd> (first tab).
